FROM golang:1.19.4 AS builder

WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download
COPY . /app
RUN make devcontainer-shell-agent

FROM scratch
COPY --from=builder /app/devcontainer-shell-agent /devcontainer-shell-agent
ENTRYPOINT ["/devcontainer-shell-agent"]
